config/routes.rb
Rails.application.routes.draw do
  resources :questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#welcome'
  get 'portfolio' => 'portfolio#index'
  get 'about' => 'about#index'
  get 'contact' => 'contact#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome; end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
    @portfolio = Project.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:author, :title, :description)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/about/index.html.erb
<div class="container row">
  <img class="img-responsive col-md-6" src="https://i.imgur.com/khW9ELv.jpg" alt="Me">
  <h3 class="col-md-6">I'm fresh-new web developer.<br>My journey started in May 2018.</h3>
</div>

<div class="container row">
  <div class="col-md-4">
    <h3>Languages I speak</h3>
    <ul>
      <li>Ruby</li>
      <li>HTML5</li>
      <li>CSS3</li>
      <li>Git</li>
      <li>SQL</li>
    </ul>
  </div>
  <div class="col-md-4">
    <h3>Dev Tools I use</h3>
    <ul>
      <li>Ruby On Rails</li>
      <li>Bootstrap</li>
      <li>Github</li>
      <li>Gitlab</li>
      <li>Terminal</li>
    </ul>
  </div>
</div>

app/views/contact/index.html.erb
<div class="container text-center">
  <h1><strong>Contact me</strong></h1>
  <a href="#"><i class="far fa-envelope glyphicon_contact"></i></a>
  <a href="https://github.com/K4cpersky"><i class="fab fa-github glyphicon_contact"></i></a>
  <a href="https://www.linkedin.com/in/kacper-m%C4%99karski-800a8a142/"><i class="fab fa-linkedin glyphicon_contact"></i></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewPortfolio</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Welcome", root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Portfolio", portfolio_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
    </div>
  </nav>
  <body>
    <%= yield %>
  </body>
  <footer class="container-fluid text-right">
    <a href="#"><i class="far fa-envelope glyphicon"></i></a>
    <a href="https://github.com/K4cpersky"><i class="fab fa-github glyphicon"></i></a>
    <a href="https://www.linkedin.com/in/kacper-m%C4%99karski-800a8a142/"><i class="fab fa-linkedin glyphicon"></i></a><br>
    <p class="footer"><i class="fas fa-copyright"></i> 2018 Kacper Mekarski </p>
  </footer>
</html>

app/views/pages/welcome.html.erb
<div class="container text-left">
  <h2>Hello!<br>My name is Kacper Mekarski.<br>I found my passion in creating web applications.<br>I work each day to become better me today than yesterday.</h2>
  <%= link_to "View my work", portfolio_path, class: "btn btn-default" %>
</div>

app/views/portfolio/index.html.erb
<div class="row container">
  <% @portfolio.each do |p| %>
<div class="col-md-10">
     <%= link_to(p.link) do %>
    <div class="thumbnail">
      <img src="<%= p.image %>">
      <div class="caption text-center">
        <h3><%= p.title %></h3>
        <p><%= p.description %></p>
      </div>
    </div>
     <% end %>
  </div>
  <% end %>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.author %></td>
        <td><%= question.title %></td>
        <td><%= question.description %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @question.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>